#!/bin/bash
# makepdf
# Use pandoc to convert a text-based document to PDF

readonly SCRIPT=$(basename "$0")
readonly ARG="$@"

function usage() {
  cat <<- EOF
Usage: $SCRIPT FILENAME [OPTION]... 
Converts FILENAME to a pdf file.

OPTIONS
  -h, --help  Display this help and exit

EOF
}

function check_args() {
  if [ $# -ne 1 ]; then
    usage
    exit 1
  elif [ "$1" = '--help' ] || [ "$1" = '-h' ]; then
    usage
    exit 0
  elif [ ! -e "$1" ]; then
    echo "$SCRIPT: can't find '$1'"
    exit 1
  fi
}

function main() {
  check_args $ARG
  local output="${ARG%.*}.pdf"
  local font="DejaVu"

  pandoc "$ARG" -o "${output}" \
    -V mainfont="${font} Serif" \
    -V sansfont="${font} Sans" \
    -V monofont="${font} Sans Mono" \
    -V "geometry:margin=1in" \
    --pdf-engine=xelatex
}
main
